accountStorage/urls.py
from django.urls import path
from accountStorage.views import login, account, server

app_name = 'accountStorage'
urlpatterns = [
    # 登录
    path('login/', login.login, name='login'),
    path('logout/', login.logout, name='logout'),
    path('image/code/', login.image_code, name='image_code'),
    # 注册
    path('register/', login.register, name='register'),
    # 账号密码列表
    path('list/', account.account_list, name='account_list'),
    path('add/', account.account_add, name='account_add'),
    path('detail/', account.account_detail, name='account_detail'),
    path('edit/', account.account_edit, name='account_edit'),
    path('delete/', account.account_delete, name='account_delete'),
    # 账号模板上传
    path('ajax/', account.upload_ajax_excel, name='upload_ajax_excel'),
    # 服务器列表
    path('server/', server.server_list, name='server_list'),
    path('server/add/', server.server_add, name='server_add'),
    path('server/detail/', server.server_detail, name='server_detail'),
    path('server/edit/', server.server_edit, name='server_edit'),
    path('server/delete/', server.server_delete, name='server_delete'),
    # 服务器模板上传
    path('server/upload/', server.upload_ajax_excel, name='server_upload'),

]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('account/', include('accountStorage.urls')),
    path('file/', include('fileStorage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.Results.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

accountStorage/models.py
from django.db import models
# from django.contrib.auth.hashers import make_password
from .untils.hash import md5
import os, uuid


# import os, uuid

class AdminUser(models.Model):
    """登录系统的账号密码"""
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=128)
    name = models.CharField(verbose_name="名称", max_length=32, blank=True, null=True)

    def __str__ (self):
        return self.username

    """重新配置password字段，使用md5或者pbkdf2加密算法保存"""

    def save (self, *args, **kwargs):
        self.password = md5(self.password)
        # self.password = make_password(self.password, None, 'pbkdf2_sha256')
        super(AdminUser, self).save(*args, **kwargs)


class AccountPassword(models.Model):
    """账号密码表"""
    name = models.CharField(verbose_name="名称", max_length=32, primary_key=False)
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=128)
    note = models.CharField(verbose_name="备注", max_length=128, blank=True, null=True)

    def __str__ (self):
        return self.username


class ServerInfo(models.Model):
    """主机信息表"""
    hostname = models.CharField(verbose_name="主机名", max_length=32, primary_key=True)
    ipaddress = models.GenericIPAddressField(verbose_name="IP地址")
    platform_choices = (
        ("Liunx", "Liunx"),
        ("Windows", "Windows"),
        ("MacOS", "MacOS"),
        ("Unix", "Unix"),
        ("Other", "Other"),
    )
    platform = models.CharField(verbose_name="平台", max_length=32, choices=platform_choices, default="Linux")
    protocol_choices = (
        ("ssh", "ssh"),
        ("rdp", "rdp"),
        ("telnet", "telnet"),
        ("vnc", "vnc"),
    )
    protocols = models.CharField(verbose_name="协议", max_length=32, choices=protocol_choices, default="ssh")
    port = models.PositiveIntegerField(verbose_name="端口")
    credentials = models.ForeignKey(verbose_name="账户凭证", to=AccountPassword, on_delete=models.SET_NULL, blank=True,
                                    null=True)
    note = models.CharField(verbose_name="备注", max_length=128, blank=True, null=True)


def user_directory_path (instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    return os.path.join("files", filename)
#
#
# class File(models.Model):
#     """文件信息"""
#     file = models.FileField(upload_to=user_directory_path, null=True)
#     upload_method = models.CharField(max_length=20, verbose_name="上传方法")

accountStorage/forms.py
from django import forms
from .models import AccountPassword
#from django.contrib.auth.hashers import make_password

from django.conf import settings
import hashlib

def md5(data_string):
    obj = hashlib.md5(settings.SECRET_KEY.encode("utf-8"))
    obj.update(data_string.encode("utf-8"))
    return obj.hexdigest()

def pbkdf2(data_string):
    return make_password(data_string, None, 'pbkdf2_sha256')

class Bootstrap():
    # password = forms.CharField(min_length=6, label="密码")
    def __init__ (self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for k, v in self.fields.items():
            if k == "create_time":
                v.widget.attrs = {"class": "form-control", "type": "text", "onclick": "WdatePicker({el:this,dateFmt:'yyyy-MM-dd'})", "placeholder": v.label}
                continue
            v.widget.attrs = {"class": "form-control", "placeholder": v.label}

class BootstrapModelForm(Bootstrap, forms.ModelForm):
    pass

class BootstrapForm(Bootstrap, forms.Form):
    pass

#######  modelform  #################

class UserModelForm(BootstrapModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = AccountPassword
        fields = ["name", "username", "password", "note"]

class LoginForm(BootstrapForm):
    username = forms.CharField(
        label="用户",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput,
        required=True
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)
        #return pbkdf2(pwd)

accountStorage/views.py
import pandas as pd
import random
from PIL import Image, ImageDraw, ImageFont, ImageFilter
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect,HttpResponse
from django.views.decorators.csrf import csrf_exempt
from io import BytesIO
from .forms import UserModelForm, LoginForm
from .models import AccountPassword,AdminUser

def login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'accountStorage/login.html', {"form": form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data)
        #去数据库校验账号密码
        user_input_code = form.cleaned_data.pop('code')
        image_code = request.session.get('image_code', "")
        if image_code.upper() != user_input_code.upper():
            form.add_error("code", "验证码错误")
            return render(request, 'accountStorage/login.html', {"form": form})
        admin_project = AdminUser.objects.filter(**form.cleaned_data).first()
        if not admin_project:
            form.add_error("password", "用户名或密码错误")
            return render(request, 'accountStorage/login.html', {"form": form})
        # 用户名密码正确 网站生成随机字符串 存到用户cookie中，写入session中
        request.session["info"] = {'id': admin_project.id, 'username': admin_project.username}
        request.session.set_expiry(60 * 60 * 24 * 7)
        return redirect("/account/")
    return render(request, 'accountStorage/login.html')
def logout(request):
    """注销"""
    request.session.clear()
    return redirect("/account/login/")

def check_code (width=120, height=30, char_length=5, font_file='Monaco.ttf', font_size=28):
    code = []
    img = Image.new(mode='RGB', size=(width, height), color=(255, 255, 255))
    draw = ImageDraw.Draw(img, mode='RGB')

    def rndChar ():
        """
        生成随机字母
        :return:
        """
        return chr(random.randint(65, 90))

    def rndColor ():
        """
        生成随机颜色
        :return:
        """
        return (random.randint(0, 255), random.randint(10, 255), random.randint(64, 255))

    # 写文字
    font = ImageFont.truetype(font_file, font_size)
    for i in range(char_length):
        char = rndChar()
        code.append(char)
        h = random.randint(0, 4)
        draw.text([i * width / char_length, h], char, font=font, fill=rndColor())

    # 写干扰点
    for i in range(40):
        draw.point([random.randint(0, width), random.randint(0, height)], fill=rndColor())

    # 写干扰圆圈
    for i in range(40):
        draw.point([random.randint(0, width), random.randint(0, height)], fill=rndColor())
        x = random.randint(0, width)
        y = random.randint(0, height)
        draw.arc((x, y, x + 4, y + 4), 0, 90, fill=rndColor())

    # 画干扰线
    for i in range(5):
        x1 = random.randint(0, width)
        y1 = random.randint(0, height)
        x2 = random.randint(0, width)
        y2 = random.randint(0, height)

        draw.line((x1, y1, x2, y2), fill=rndColor())

    img = img.filter(ImageFilter.EDGE_ENHANCE_MORE)
    return img, ''.join(code)

def image_code(request):
    """生成图片验证码"""
    # 调用pillow函数 生产图片
    img, code_string = check_code()
    # 写入到自己的session中,60秒过期
    request.session['image_code'] = code_string
    request.session.set_expiry(60)
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

def account_list (request):
    """用户列表"""
    # for i in range(20):
    #     account = {
    #         "name": "测试账号{}".format(i),
    #         "username": "test{}".format(i),
    #         "password": "123456".format(i),
    #         "note": "测试备注{}".format(i)
    #     }
    #     AccountPassword.objects.create(**account)
    #     AccountPassword.objects.filter(username="test{}".format(i)).delete()
    data = {}
    search_data = request.GET.get('search', "")
    if search_data:
        data["username__contains"] = search_data
    form = UserModelForm()
    data_list = AccountPassword.objects.filter(**data).order_by("-id")
    paginator = Paginator(data_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    keys = AccountPassword._meta.fields
    keys_list = [keys[i].name for i in range(len(keys))]
    context = {
        "title": "账号列表",
        "search_data": search_data,
        "key_list": keys_list,
        "data_list": data_list,
        "page_obj": page_obj,
        "form": form,
        "excel_url": "/media/excel/account.xlsx",
    }
    return render(request, 'accountStorage/account.html', context)


@csrf_exempt
def account_add (request):
    """添加用户 (ajax请求)"""
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        # 随机生成订单号
        # form.instance.oid = datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000, 9999))
        # form.instance.admin_id = request.session['info']['id']
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})


def account_detail (request):
    """获取账号详情"""
    uid = request.GET.get("uid")
    row_dict = AccountPassword.objects.filter(id=uid).values("name", "username", "password", "note").first()
    if not row_dict:
        return JsonResponse({"status": False, 'error': "数据不存在"})
    result = {"status": True, 'data': row_dict}
    return JsonResponse(result)



@csrf_exempt
def account_edit (request):
    """账号编辑"""
    uid = request.GET.get("uid")
    row_object = AccountPassword.objects.filter(id=uid).first()
    if not row_object:
        return JsonResponse({"status": False, 'tips': "数据不存在"})
    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, 'error': form.errors})

@csrf_exempt
def account_delete (request):
    """账号删除"""
    uid = request.GET.get('uid')
    exists = AccountPassword.objects.filter(id=uid).exists()
    if not exists:
        return JsonResponse({"status": False, 'error': "删除失败，数据不存在"})
    AccountPassword.objects.filter(id=uid).delete()
    return JsonResponse({"status": True, 'msg': "删除成功"})

@csrf_exempt
def upload_excel (request):
    """上传excel，读取数据写入数据库"""
    if request.method == 'POST':
        raw_file = request.FILES.get('file')
        print(raw_file)
        df = pd.read_excel(raw_file)
        print(df)
        df.fillna("", inplace=True)
        print(df.index.name)
        for i in df.index.values:
            df_dict = df.loc[i, ["name", "username", "password", "note"]].to_dict()
            print(df_dict)
            AccountPassword.objects.create(**df_dict)
        return redirect("/account/")
    return render(request, 'accountStorage/upload_excel.html')


@csrf_exempt
def upload_ajax_excel (request):
    """ajax上传excel，读取数据写入数据库"""
    if request.method == 'POST':
        file_object = request.FILES.get('files')
        df = pd.read_excel(file_object, keep_default_na=False)
        print(df)
        for i in df.index.values:
            df_dict = df.loc[i, ["name", "username", "password", "note"]].to_dict()
            print(df_dict)
            AccountPassword.objects.create(**df_dict)
        return redirect("/account/")
    return render(request, 'accountStorage/ajax_upload.html')

accountStorage/views/account.py
import pandas as pd
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from accountStorage.untils.forms import UserModelForm
from accountStorage.models import AccountPassword
from accountStorage.untils.auth import login_check


@login_check
def account_list(request):
    """用户列表"""
    # for i in range(20):
    #     account = {
    #         "name": "测试账号{}".format(i),
    #         "username": "test{}".format(i),
    #         "password": "password{}".format(i),
    #         "note": "测试备注{}".format(i)
    #     }
    #     AccountPassword.objects.create(**account)
    #     AccountPassword.objects.filter(username="test{}".format(i)).delete()
    data = {}
    search_data = request.GET.get('search', "")
    if search_data:
        data["username__contains"] = search_data
    form = UserModelForm()
    data_list = AccountPassword.objects.filter(**data).order_by("id")
    paginator = Paginator(data_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    keys = AccountPassword._meta.fields
    keys_list = [keys[i].verbose_name for i in range(len(keys))]
    # keys_list = [keys[i].name for i in range(len(keys))]
    context = {
        "title": "账号列表",
        "search_data": search_data,
        "key_list": keys_list,
        "data_list": data_list,
        "page_obj": page_obj,
        "form": form,
        "excel_url": "/media/excel/account.xlsx",
    }
    return render(request, 'accountStorage/account.html', context)


@login_check
@csrf_exempt
def account_add(request):
    """添加用户 (ajax请求)"""
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})


@login_check
def account_detail(request):
    """获取账号详情"""
    account_id = request.GET.get("id")
    row_dict = AccountPassword.objects.filter(id=account_id).values("name", "username", "password", "note").first()
    if not row_dict:
        return JsonResponse({"status": False, 'error': "数据不存在"})
    result = {"status": True, 'data': row_dict}
    return JsonResponse(result)


@login_check
@csrf_exempt
def account_edit(request):
    """账号编辑"""
    account_id = request.GET.get("id")
    row_object = AccountPassword.objects.filter(id=account_id).first()
    if not row_object:
        return JsonResponse({"status": False, 'tips': "数据不存在"})
    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, 'error': form.errors})


@login_check
@csrf_exempt
def account_delete(request):
    """账号删除"""
    account_id = request.GET.get('id')
    if not AccountPassword.objects.filter(id=account_id).exists():
        return JsonResponse({"status": False, 'error': "删除失败，数据不存在"})
    AccountPassword.objects.filter(id=account_id).delete()
    return JsonResponse({"status": True, 'msg': "删除成功"})


@login_check
@csrf_exempt
def upload_ajax_excel(request):
    """ajax上传excel，读取数据写入数据库"""
    if request.method == 'POST':
        file_object = request.FILES.get('files')
        df = pd.read_excel(file_object, keep_default_na=False)
        print(df)
        for i in df.index.values:
            df_dict = df.loc[i, ["name", "username", "password", "note"]].to_dict()
            print(df_dict)
            AccountPassword.objects.create(**df_dict)
        return redirect("accountStorage:account_list")
    return JsonResponse({'status': False, 'error': 'excel异常'})

accountStorage/templates/accountStorage/server.html
{% extends 'accountStorage/layout.html' %}
{% block content %}
    <button type="button" class="btn btn-success" onclick="AddEvent()">新建服务器</button>
    <button type="button" class="btn btn-primary" data-toggle="modal" onclick="UploadEvent()">模板上传</button>
    <!-- 搜索框 -->
    <div style="float: right;width: 300px">
        <form method="get">
            <div class="input-group">
                <label>
                    <input type="text" class="form-control" placeholder="搜 主机名" name="search"
                           value="{{ search_data }}"/>
                </label>
                <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
                </span>
            </div>
        </form>
    </div>
    <!-- 显示服务器列表 -->
    <div class="bs-example" data-example-id="hoverable-table">
        <table class="table table-hover">
            <thead>
            <tr>
                {% for key in key_list %}
                    {% if key != '账户凭证' %}
                        <th>{{ key }}</th>
                    {% endif %}
                {% endfor %}
                <th>账号</th>
                <th>密码</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for data in page_obj %}
                <tr>
                    <td>{{ data.hostname }}</td>
                    <td>{{ data.ipaddress }}</td>
                    <td>{{ data.get_platform_display }}</td>
                    <td>{{ data.get_protocols_display }}</td>
                    <td>{{ data.port }}</td>
                    <td>{{ data.note|default_if_none:"" }}</td>
                    <!--<td>{{ data.credentials.name }}</td>-->
                    <td>
                        {% if data.credentials.username %}
                            {{ data.credentials.username }}
                        {% else %}
                            <span class="label label-warning">未配置</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if data.credentials.password %}
                            <button class="btn btn-info btn-xs" onclick="copyToClip('{{ data.credentials.password }}')">
                                Copy
                            </button>
                        {% endif %}
                    </td>
                    <td>
                        <a class="btn btn-primary btn-xs btn-edit" onclick="editServer('{{ data.hostname }}')">编辑</a>
                        <a class="btn btn-danger btn-xs btn-delete" onclick="DeleteServer('{{ data.hostname }}')">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- 添加/编辑服务器Modal -->
    <div class="modal fade" id="modalAddEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="modalAddEditLabel">title</h4>
                </div>
                <div class="modal-body">
                    <form id="formAddEdit" novalidate class="form-horizontal">
                        <div class="clearfix">
                            {% for i in form %}
                                <div class="col-xs-12">
                                    <div class="form-group" style="position: relative;margin-bottom: 20px">
                                        <label>{{ i.label }}</label>
                                        {{ i }}
                                        <span class="error-msg" style="color: red;position: absolute"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary" onclick="BtnSaveEvent()">保存</button>
                </div>
            </div>
        </div>
    </div>
    <!-- 删除服务器Modal -->
    <div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否删除该服务器？</h4>
                <p>删除后，相关服务器信息将会消失！</p>
                <p style="text-align: right;">
                    <button type="button" class="btn btn-danger" onclick="ConfirmDeleteServer()">确定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                </p>
            </div>
        </div>
    </div>
    <!-- 上传Small modal -->
    <div class="modal fade" id="modalUpload" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <p>
                    <a href="{{ excel_url }}">模板下载</a>
                    <input type="file" class="form-control" name="upload" id="file_uploads" required/>
                </p>
                <button class="btn btn-info form-control" type="submit" onclick="uploads()" value="submit">上传
                </button>
            </div>
        </div>
    </div>
    <!-- 分页 -->
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1&search={{ search_data }}">&laquo; 首页</a>
            <a href="?page={{ page_obj.previous_page_number }}&search={{ search_data }}">上一页</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>
        <a href="?page={{ page_obj.start_index }}&search={{ search_data }}">{{ page_obj.number }}</a>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&search={{ search_data }}">下一页</a>
            <a href="?page={{ page_obj.paginator.num_pages }}&search={{ search_data }}">尾页 &raquo;</a>
        {% endif %}
    </span>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        let HOSTNAME;

        //点击新建弹出
        function AddEvent() {
            // 将正在编辑的ID设置为空
            HOSTNAME = undefined;
            // 清空对话框内容
            $("#formAddEdit")[0].reset();
            // 修改对话框标题
            $("#modalAddEditLabel").text("新建");
            // 显示新建账号模态框
            $('#modalAddEdit').modal('show');
            //清空可能残留的错误
            $(".error-msg").empty();
        }

        //点击编辑弹出
        function editServer(content) {
            // 编辑服务器信息
            HOSTNAME = content
            $.ajax({
                url: "{% url 'accountStorage:server_detail' %}",
                type: "get",
                data: {
                    hostname: content
                },
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        //将数据赋值到标签中
                        $.each(res.data, function (name, value) {
                            $("#id_" + name).val(value)
                        })
                        //修改对话框标题
                        $("#modalAddEditLabel").text("编辑")
                        //点击编辑按钮，显示对话框
                        $('#modalAddEdit').modal('show');
                        //清空可能残留的错误
                        $(".error-msg").empty();
                    } else {
                        alert(res.error);
                    }
                }

            })

        }

        //点击保存，根据HOSTNAME来执行脚本
        function BtnSaveEvent() {
            // 清除错误信息
            $(".error-msg").empty();
            // 变量HOSTNAME存在则是编辑，不存在则是新建
            if (HOSTNAME) {
                EditServer();
            } else {
                AddServer();
            }
        }

        //新增服务器
        function AddServer() {
            //点击保存按钮，发生请求
            $.ajax({
                url: "{% url 'accountStorage:server_add' %}",
                type: "post",
                data: $("#formAddEdit").serialize(),
                dataType: 'JSON',
                success: function (res) {
                    if (res.status) {
                        //刷新页面
                        location.reload();
                    } else {
                        // 把错误信息显示在对话框中
                        $.each(res.error, function (name, errorList) {
                            $("#id_" + name).next().text(errorList[0]);
                        })
                    }
                }
            })
        }

        //编辑服务器
        function EditServer() {
            //点击保存按钮，发生请求/server/edit/?hostname=xx
            $.ajax({
                url: "{% url 'accountStorage:server_edit' %}" + "?hostname=" + HOSTNAME,
                type: "post",
                data: $("#formAddEdit").serialize(),
                dataType: 'JSON',
                success: function (res) {
                    if (res.status) {
                        location.reload();
                    } else {
                        if (res.tips) {
                            alert(res.tips);
                        } else {
                            // 把错误信息显示在对话框中
                            $.each(res.error, function (name, errorList) {
                                $("#id_" + name).next().text(errorList[0]);
                            })
                        }
                    }
                }
            })
        }

        //点击删除按钮，显示对话框
        function DeleteServer(content) {
            $('#modalDelete').modal('show');
            HOSTNAME = content
            console.log('询问删除 ' + HOSTNAME);
        }

        //点击确定删除按钮，发送ajax请求删除数据
        function ConfirmDeleteServer() {
            console.log('确定删除' + HOSTNAME);
            $.ajax({
                url: "{% url 'accountStorage:server_delete' %}",
                type: "get",
                data: {
                    hostname: HOSTNAME
                },
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        //删除成功信息
                        console.log(HOSTNAME + ' 删除成功');
                        HOSTNAME = undefined
                        //刷新页面
                        location.reload()

                    } else {
                        //删除失败
                        alert(res.error)
                        location.reload()
                    }
                }
            });
        }

        //显示上传模态框
        function UploadEvent() {
            $('#modalUpload').modal('show');
        }

        //上传excel
        function uploads() {
            const form_data = new FormData();
            form_data.append('files', $('#file_uploads')[0].files[0]);
            $.ajax({
                url: "{% url 'accountStorage:server_upload' %}",
                type: 'post',
                contentType: false,
                processData: false,
                data: form_data,
                success: function () {
                    alert('上传完成!')
                    location.reload();
                }
            })
        }

        //点击复制
        function copyToClip(content, message) {
            let aux = document.createElement("input");
            aux.setAttribute("value", content);
            document.body.appendChild(aux);
            aux.select();
            document.execCommand("copy");
            document.body.removeChild(aux);
            if (message == null) {
                console.log("复制成功");
                //alert("复制成功");
            } else {
                alert(message);
            }
        }


    </script>
{% endblock %}