djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('account/', include('accountStorage.urls')),
    path('file/', include('fileStorage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fileStorage/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'fileStorage'
urlpatterns = [
    # 账号密码
    path('', views.file_list, name='file_list'),
    re_path(r'^file/upload1/$', views.file_upload, name='form_upload'),
    re_path(r'^file/upload2/$', views.model_form_upload, name='model_form_upload'),
    path(r'ajax/', views.ajax_upload, name='ajax_upload'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.Results.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

fileStorage/models.py
# import os
# import uuid
from django.db import models


# def user_directory_path(instance, filename):
#     """定义路径名"""
#     ext = filename.split('.')[-1]
#     filename = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
#     return os.path.join("files", filename)


class File(models.Model):
    """文件信息"""
    name = models.CharField(max_length=20, verbose_name="自定义名")
    file = models.FileField(upload_to="media/%Y-%m-%d", null=True, verbose_name="文件路径")
    # file = models.FileField(upload_to=user_directory_path, null=True, verbose_name="文件路径")
    annotation = models.CharField(max_length=20, verbose_name="备注", null=True)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="上传时间")

fileStorage/forms.py
from django import forms
from .models import File


# form
class FileUploadForm(forms.Form):
    name = forms.CharField(label="名称", max_length=20,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    annotation = forms.CharField(label="备注", max_length=20,
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_file(self):
        file = self.cleaned_data['file']
        # # 限制上传后缀
        # ext = file.name.split('.')[-1].lower()
        # if ext not in ["jpg", "pdf", "xlsx"]:
        #     raise forms.ValidationError("不支持的文件格式")
        return file


# Model form
class FileUploadModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('name', 'file', 'annotation',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'annotation': forms.TextInput(attrs={'class': 'form-control'}),
            'file': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def clean_file(self):
        file = self.cleaned_data['file']
        # # 限制上传后缀
        # ext = file.name.split('.')[-1].lower()
        # if ext not in ["jpg", "pdf", "xlsx"]:
        #     raise forms.ValidationError("Only jpg, pdf and xlsx files are allowed.")
        # return cleaned data is very important.
        return file

fileStorage/views.py
import os
import uuid
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from .forms import FileUploadForm, FileUploadModelForm
from .models import File


def file_list(request):
    """文件列表"""
    files = File.objects.all().order_by('-id')
    return render(request, 'fileStorage/file_list.html', {'files': files})


def handle_uploaded_file(file):
    ext = file.name.split(',')[-1]
    file_name = "{}.{}".format(uuid.uuid4().hex[:10], ext)
    file_path = os.path.join('media', 'files', file_name)
    absolute_file_path = os.path.join('media', 'files', file_name)
    directory = os.path.dirname(absolute_file_path)
    if not os.path.exists(directory):
        os.makedirs(directory)

    with open(absolute_file_path, 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)

    return file_path


def file_upload(request):
    """使用from上传"""
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            annotation = form.cleaned_data.get("annotation")
            raw_file = form.cleaned_data.get('file')
            new_file = File()
            new_file.file = handle_uploaded_file(raw_file)
            new_file.name = name
            new_file.annotation = annotation
            new_file.save()
            return redirect("/file/")
    else:
        form = FileUploadForm()
    return render(request, 'fileStorage/upload_form.html', {'form': form, 'heading': 'Upload files with Regular Form'})


def model_form_upload(request):
    """使用modelfrom上传"""
    if request.method == "POST":
        form = FileUploadModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()  # 一句话足以
            return redirect("/file/")
    else:
        form = FileUploadModelForm()

    return render(request, 'fileStorage/upload_form.html',
                  {'form': form, 'heading': 'Upload files with ModelForm'}
                  )


@csrf_exempt
def ajax_upload(request):
    """ajax上传文件，路径写入数据库"""
    if request.method == "POST":
        file_name = request.POST.get('name')
        file_object = request.FILES.get('files')
        file_annotation = request.POST.get('annotation')
        print(file_name, file_object, file_annotation)
        new_file = File()
        new_file.file = file_object
        new_file.name = file_name
        new_file.annotation = file_annotation
        new_file.save()
        return redirect("/file/")

fileStorage/templates/fileStorage/file_list.html
{% extends 'fileStorage/layout.html' %}
{% block content %}
    <h3>三种方式</h3>
    <p><a href="{% url 'fileStorage:form_upload' %}"> From上传 </a> | <a href="{% url 'fileStorage:model_form_upload' %}">
        ModelForm上传 </a>
        | <a onclick="UploadEvent()"> Ajax上传 </a></p>
    {% if files %}
        <table class="table table-striped">
            <tbody>
            <tr>
                <td>Filename & URL</td>
                <td>Filesize</td>
                <td>Upload Method</td>
            </tr>
            {% for file in files %}
                <tr>
                    <img src="{{ file.file.url }}" width="980" height="180"/>
                    <td>{{ file.name }}</td>
                    <td><a href="{{ file.file.url }}">{{ file.file.url }}</a></td>
                    <td>{{ file.file.size | filesizeformat }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% else %}

        <p>No files uploaded yet. Please click <a href="{% url 'fileStorage:form_upload' %}">here</a>
            to upload files.</p>
    {% endif %}
    <!-- 上传Small modal -->
    <div class="modal fade" id="modalUpload" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <p>
                    <label for="file_name">名称:</label><input type="text" class="form-control" name="file_name"
                                                             id="file_name" value="" required/>
                    <input type="file" class="form-control" name="upload" id="file_uploads" required/>
                    <label for="file_annotation">备注:</label><input type="text" class="form-control"
                                                                   name="file_annotation" id="file_annotation" value=""
                                                                   required/>
                </p>
                <button id="btnUploadExcel" class="btn btn-info form-control" type="submit" onclick="uploads()"
                        value="submit">上传
                </button>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        function UploadEvent() {
            $('#modalUpload').modal('show');
        }

        function uploads() {
            const form_data = new FormData();
            form_data.append('name', $('#file_name').val());
            form_data.append('files', $('#file_uploads')[0].files[0]);
            form_data.append('annotation', $('#file_annotation').val());
            $.ajax({
                url: "{% url 'fileStorage:ajax_upload' %}",
                type: 'post',
                contentType: false,
                processData: false,
                data: form_data,
                success: function (callback) {
                    alert('上传完成!')
                    location.reload();
                }
            })
        }
    </script>
{% endblock %}

fileStorage/templates/fileStorage/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'fileStorage/plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'fileStorage:file_list' %}">测试上传方法</a>
        </div>
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
{% block content %}{% endblock %}
</div>
<script src="{% static 'fileStorage/js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'fileStorage/plugins/bootstrap-3.4.1-dist/js/bootstrap.js' %}"></script>
<script src="{% static 'fileStorage/plugins/bootstrap-3.4.1-dist/js/WdatePicker.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

fileStorage/templates/fileStorage/upload_form.html
{% extends 'fileStorage/layout.html' %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  {{ form.as_p }}
 <button class="btn btn-info form-control " type="submit" value="submit">Upload</button>
</form>
{% endblock %}